apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque

stringData:
  DB_USER: "sqladmin"
  DB_PASSWORD: "SQLP@ssword!23!"
  DB_SERVER: "uat-cloudops-sql1.database.windows.net"
  DB_NAME: "uat_cloudops_db1"