apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 3000


# kubectl apply -f ./service.yaml